# -*- coding: utf-8 -*-
"""GenAI app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JOaR4nceJbqT3q4Jit8VXpoPixyL8CZP
"""

from google import genai

client = genai.Client(api_key='AIzaSyDdoiLDVKQ1S_jMjG_WzNDZQ6_jcDDPRWw')

response = client.models.generate_content(
    model="gemini-3-flash-preview",
    contents="Exaplain between Mannheim busisness school and Franfurt school of finance which is better for finance, job opportunities and internationalization",
)

print(response.text)

# Ensure response.text is a string before writing to file
output_text = response.text if response.text is not None else ""

with open('response.txt', 'w') as f:
    f.write(output_text)